version: "3.6"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ddzb-data:/var/lib/postgresql/data/
      - ./scripts/docker-compose/provision_maindb.sql:/docker-entrypoint-initdb.d/1_provision_maindb.sql
    restart: unless-stopped
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  ddzb-data: