# fly.toml app configuration file generated for doudizhubot on 2024-03-07T18:31:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'doudizhubot'
primary_region = 'atl'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
